apiVersion: apps/v1
kind: Deployment
metadata:
  name: show-container
spec:
  selector:
    matchLabels:
      app: show-container
  replicas: 2
  template:
    metadata:
      labels:
        app: show-container
    spec:
      containers:
        - name: show-container
          image: ralphbaesso/show-container
          ports:
            - containerPort: 4567

---
apiVersion: v1
kind: Service
metadata:
  name: show-container
spec:
  type: ClusterIP
  selector:
    app: show-container
  ports:
    - port: 80
      targetPort: 4567

---
apiVersion: v1
kind: Service
metadata:
  name: show-container-inner
spec:
  type: NodePort
  selector:
    app: show-container
  ports:
    - port: 80
      targetPort: 4567
      nodePort: 30000

---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: show-container-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
#    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  rules:
    - host: show.ingress.extramed.com.br
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: show-container-service
                port:
                  number: 80

    - host: show123.ingress.extramed.com.br
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: show-container-service
                port:
                  number: 80
