apiVersion: v1
kind: Service
metadata:
  name: legacy-canal-corretor
  namespace: legacy
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  clusterIP: None
  type: ClusterIP

---
apiVersion: v1
kind: Endpoints
metadata:
  name: legacy-canal-corretor
  namespace: legacy
subsets:
  - addresses:
      - ip: 192.168.90.41
    ports:
      - name: http
        port: 80
        protocol: TCP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: legacy-canal-corretor
  namespace: legacy
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/stream-snippet: |
      server {
        location / {
                client_max_body_size 100M;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

                # WebSocket support (nginx 1.4)
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
        }
      }
spec:
  ingressClassName: nginx
  rules:
    - host: canalcorretor.extramed.com.br
      http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: legacy-canal-corretor
                port:
                  number: 80
            path: /
  tls:
    - hosts:
        - canalcorretor.extramed.com.br
      secretName: legacy-canal-corretor-cert
