apiVersion: v1
kind: Service
metadata:
  name: legacy-canal-corretor
  namespace: legacy
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  clusterIP: None
  type: ClusterIP

---
apiVersion: v1
kind: Endpoints
metadata:
  name: legacy-canal-corretor
  namespace: legacy
subsets:
  - addresses:
      - ip: 192.168.90.41
    ports:
      - name: http
        port: 80
        protocol: TCP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: legacy-canal-corretor
  namespace: legacy
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-body-size: 100M
spec:
  ingressClassName: nginx
  rules:
    - host: canalcorretor.extramed.com.br
      http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: legacy-canal-corretor
                port:
                  number: 80
            path: /
  tls:
    - hosts:
        - canalcorretor.extramed.com.br
      secretName: legacy-canal-corretor-cert
