apiVersion: v1
kind: Service
metadata:
  name: legacy-corretordigitalextramed
  namespace: legacy
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 32080
  clusterIP: None
  type: ClusterIP

---
apiVersion: v1
kind: Endpoints
metadata:
  name: legacy-corretordigitalextramed
  namespace: legacy
subsets:
  - addresses:
      - ip: 192.168.90.2
    ports:
      - name: http
        port: 32080
        protocol: TCP

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: legacy-corretordigitalextramed-www-cert
  namespace: legacy
  labels:
    "use-http01-solver": "true"
spec:
  commonName: www.corretordigitalextramed.com.br
  secretName: legacy-corretordigitalextramed-www-cert
  dnsNames:
    - www.corretordigitalextramed.com.br
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: legacy-corretordigitalextramed-www
  namespace: legacy
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`www.corretordigitalextramed.com.br`)
      services:
        - name: legacy-corretordigitalextramed
          port: 80
  tls:
    secretName: legacy-corretordigitalextramed-www-cert

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: legacy-corretordigitalextramed-root-cert
  namespace: legacy
  labels:
    "use-http01-solver": "true"
spec:
  commonName: corretordigitalextramed.com.br
  secretName: legacy-corretordigitalextramed-root-cert
  dnsNames:
    - corretordigitalextramed.com.br
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: legacy-corretordigitalextramed-root
  namespace: legacy
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`corretordigitalextramed.com.br`)
      services:
        - name: legacy-corretordigitalextramed
          port: 80
  tls:
    secretName: legacy-corretordigitalextramed-root-cert
