apiVersion: v1
kind: Service
metadata:
  name: legacy-egeon-club
  namespace: legacy
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  clusterIP: None
  type: ClusterIP

---
apiVersion: v1
kind: Endpoints
metadata:
  name: legacy-egeon-club
  namespace: legacy
subsets:
  - addresses:
      - ip: 192.168.90.12
    ports:
      - name: http
        port: 80
        protocol: TCP

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: legacy-egeon-club-cert
  namespace: legacy
  labels:
    "use-http01-solver": "true"
spec:
  commonName: egeonclub.extramed.com.br
  secretName: legacy-egeon-club-cert
  dnsNames:
    - egeonclub.extramed.com.br
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: legacy-egeon-club
  namespace: legacy
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`egeonclub.extramed.com.br`)
      priority: 10
      services:
        - name: legacy-egeon-club
          port: 80
  tls:
    secretName: legacy-egeon-club-cert
