apiVersion: v1
kind: Service
metadata:
  name: legacy-site
  namespace: legacy
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  clusterIP: None
  type: ClusterIP

---
apiVersion: v1
kind: Endpoints
metadata:
  name: legacy-site
  namespace: legacy
subsets:
  - addresses:
      - ip: 192.168.90.52
    ports:
      - name: http
        port: 80
        protocol: TCP

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: legacy-site-www-cert
  namespace: legacy
  labels:
    "use-http01-solver": "true"
spec:
  commonName: www.extramed.com.br
  secretName: legacy-site-www-cert
  dnsNames:
    - www.extramed.com.br
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: legacy-site-www
  namespace: legacy
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`www.extramed.com.br`)
      services:
        - name: legacy-site
          port: 80
  tls:
    secretName: legacy-site-www-cert

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: legacy-site-root-cert
  namespace: legacy
  labels:
    "use-http01-solver": "true"
spec:
  commonName: extramed.com.br
  secretName: legacy-site-root-cert
  dnsNames:
    - extramed.com.br
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: legacy-site-root
  namespace: legacy
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`extramed.com.br`)
      services:
        - name: legacy-site
          port: 80
  tls:
    secretName: legacy-site-root-cert
