---
apiVersion: v1
kind: Service
metadata:
  name: argoserver
spec:
  type: NodePort
  selector:
    app: argocd-server
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001
#    - port: 80
#      targetPort: 443
#      nodePort: 30002