
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: nucleoti@extramed.com.br
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - http01:
          ingress:
            class: traefik

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: show-container-cert
  namespace: default
spec:
  commonName: show.ingress.extramed.com.br
  secretName: show-container-cert
  dnsNames:
    - show.ingress.extramed.com.br
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
