ingressRoute:
  dashboard:
    enabled: true
    annotations: { traefik.ingress.kubernetes.io/router.tls: "true" }

deployment:
  kind: Deployment

logs:
  general:
    level: INFO

ports:
  web:
    redirectTo: websecure
  websecure:
    tls:
      enabled: true
  ssh:
    port: 2222
    expose: true
    exposedPort: 22
    protocol: TCP

service:
  type: NodePort

providers:
  kubernetesIngress:
    ingressClass: "traefik-cert-manager"
    ingressEndpoint:
      - 192.168.90.165
      - 192.168.90.166
      - 192.168.90.167


additionalArguments:
  - "--log.level=INFO"
  - "--entrypoints.websecure.http.tls"
  - "--providers.kubernetesIngress.ingressClass=traefik-cert-manager"
  - "--ping"
  #  - "--metrics.prometheus"
