apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: nucleoti@extramed.com.br
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource that will be used to store the account's private key.
      name: issuer-account-key
    solvers:
      - http01:
          ingress:
            class: traefik-cert-manager
        selector:
          matchLabels:
            "use-http01-solver": "true"
